Update documentation
fedora-java/javapackages-validator pull request #110
Opened 2024-07-25 15:24 UTC by mkoncek

2024-07-26 05:17 UTC, mizdebsk requested changes
`-u` is still used (issue #85), should it be removed as well?
Otherwise it looks good to me except a few minor issues.

2024-07-26 05:17 UTC, mizdebsk commented on README.adoc
> +A custom validator must implement the `org.fedoraproject.javapackages.validator.spi.Validator` interface and have its name listed in the service file on the class path of the program.
Validators are not listed in service files. Validator factories are.

2024-07-26 05:17 UTC, mizdebsk commented on README.adoc
> +If the user wants to run the validator on a list of separate `.java` or `class` files, they need to be passed via the `--cp` or the `--sp` flags.
In sentence "running validator on something", "something" is the thing validator inspects.

2024-07-26 05:17 UTC, mizdebsk commented on README.adoc
> +=== https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/ServiceLoader.html#deploying-service-providers-on-the-class-path-heading[Service file]
I would remove the link from section header and add it in the text below.

2024-07-26 11:57 UTC, mkoncek commented
I was wondering if I implement or remove the `-u` feature, but I will postpone it for now.

2024-07-29 14:36 UTC, mizdebsk approved these changes
LGTM

2024-07-29 14:36 UTC, merged