Make the run script work with multiple JVM installations
fedora-java/javapackages-validator pull request #166
Opened 2024-11-12 12:53 UTC by mkoncek

2024-11-12 13:37 UTC, mizdebsk requested changes
I think that the PR goes in a wrong direction. The `run.sh` script is used for local testing only, after doing Maven build. It even refers to the `target` directory created by Maven. Appropriate JAVA_HOME needs to be set for Maven anyway, so why not use the same JVM in run.sh? I will provide example of what I mean.

2024-11-12 13:37 UTC, mizdebsk commented on run.sh
> +set -e
You can keep `-u` and evaluate variables that can be possible unset like this: `${JAVA_HOME:-}`

2024-11-12 13:41 UTC, mizdebsk commented
> I will provide example of what I mean.

See #167 for example of what I mean as counter-proposal.

2024-11-13 11:57 UTC, mkoncek commented
Closing in favor of your solution.

2024-11-13 11:57 UTC, closed without merging